spring:
  application:
    name: concert
  datasource:
    driver-class-name:
    url: jdbc:mysql://localhost:3306/concert
    username: root
    password:

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none

  data:
    redis:
      host: localhost
      port: 6379
      timeout: 10000

  cache:
    type: redis

  kafka:
    bootstrap-servers: "localhost:9092"
    consumer:
      auto-offset-reset: earliest
      group-id: payment